<a href="https://colab.research.google.com/github/Fakhre-Alam-Hub/Data-Science-Basic/blob/master/Notes/3_Classification_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>Classification Algorithms</center>

1. Logistic Regression
2. Linear Discriminant Analysis
3. K nearest neighbor

**Why not Linear Regression for Classification problem?**

**Limitation of Linear Regression**
* Linear Regression can not be used for more than two lavels of response variable
* Linear regression is used for continous response variable.
* The predicted value of y can not be considered as a probability of belonging to a particular class.
><b>Note: probability range from 0 to 1 but linear regression output range from -1 to 1.</b>
* Impact of outline values(not outlier it is handel in preprocessing)

# Logistic Regression for single predictor

* Logistic regression is a linear model for binary classification predictive modeling.
* The linear part of the model predicts the log-odds of an example * belonging to class 1, which is converted to a probability via the logistic function.
* The parameters of the model can be estimated by maximizing a likelihood function that predicts the mean of a Bernoulli distribution for each example.

* It uses sigmoid function which range from 0 to 1
* It used when predicted variable is categorical.

Sigmoid Function $$p(X) = \frac{\epsilon^{(\beta_0+\beta_1X)}}{1+ \epsilon^{(\beta_0+\beta_1X)}}$$


* x tending towards infinity, the sigmoid function(P(x)) tending to 1
* x tending towards - infinity, the sigmoid function(P(x)) tending to 0
* For x=0, P(X) = 0.5

MODEL                 | METHOD
----------------------|-----------------------------
Linear Regression     | Ordinary Least Squares (OLS)
Logistic Regression   | Maximum Likelihood Method

# Logistic Regression For multiple Predictor

Sigmoid Function for multiple predictor $$p(X) = \frac{\epsilon^{(\beta_0+\beta_1X1+...+\beta_pXp)}}{1+ \epsilon^{(\beta_0+\beta_1X1+...+\beta_pXp)}}$$

# Confusion Matrix

[Confusion matrix image](https://miro.medium.com/max/2102/1*fxiTNIgOyvAombPJx5KGeA.png)

* **True Positives (TP):** when the actual value is Positive and predicted is also Positive.
* **True negatives (TN):** when the actual value is Negative and prediction is also Negative.
* **False positives (FP):** When the actual is negative but prediction is Positive. Also known as the Type 1 error
* **False negatives (FN):** When the actual is Positive but the prediction is Negative. Also known as the Type 2 error


## Classification Measure

**Accuracy:** It’s the ratio between the number of correct predictions and the total number of predictions. **The accuracy metric is not suited for imbalanced classes.**

Accuracy = $\frac{TP+TN}{TP+TN+FP+FN}$
<br><br>
**Precision:** Precision is defined as the ratio of the total number of correctly classified positive classes divided by the total number of predicted positive classes. Or, out of all the predictive positive classes, how much we predicted correctly. **Precision should be high(ideally 1).** “Precision is a useful metric in cases where False Positive is a higher concern than False Negatives”

Precission = $\frac{TP}{TP+FP}$
<br><br>

**Recall:** Recall is defined as the ratio of the total number of correctly classified positive classes divide by the total number of positive classes. Or, out of all the positive classes, how much we have predicted correctly. **Recall should be high(ideally 1).**
“Recall is a useful metric in cases where False Negative trumps False Positive”

Recall = $\frac{TP}{TP+FN}$
<br><br>

**Trick to remember : Precision has Predictive Results in the denominator.**
<br><br>

**F-measure / F1-Score:** There will be cases where there is no clear distinction between whether Precision is more important or Recall. We combine them!

F1-score = $2 * \frac{(Recall * Precission)}{(Recall + Precission)}$
<br><br>

True positive rate = $\frac{TP}{TP+FN}$ = 1 - Type-2 Error = Sensitivity = Recall
<br><br>
False positive rate = $\frac{FP}{TN+FP}$ = Type-1 Error = 1-Specificity


**ROC:** Receiver Operating Characteristics
>x-axis: False Positive rate

>y-axis: True Positive rate

AUC of ROC ideally be 1


# Linear Discriminant Analysis

* Preferred when response variable has more than two classes
* Based on Bayes Theorem

For a given set of predictor values LDA will calculate the probability of that observation belonging to each group, which group has highest probability that group is assigned to that observation.

#### Assumption 
* Continuos variable are normaly distributed
* **If continuos variable is normaly distributed LDA perform better otherwise Logistic regression perform better**

# K-Nearest Neighbors

* Uses bayes classifier
* Used when there is non-linear relation between predictor and response variable
* **KNN is non parametric method**
* It does not assume any functional form
* Standardization of data require

**Hyperparameter**
* **K(n_neighbors):** Low value of K means more flexible,and high value of K means less flexible

**Drawbacks**
* No functional relation in predictor variable and response variable.
* Cannot estimate the effect of individual predictor on target variable

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 

import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Data Science Notes with Example/Data Files/2. ST Academy - Classification models resource files/House-Price.csv")
df.head()

price  resid_area  air_qual  room_num  ...  rainfall  bus_ter     parks  Sold
0   24.0       32.31     0.538     6.575  ...        23      YES  0.049347     0
1   21.6       37.07     0.469     6.421  ...        42      YES  0.046146     1
2   34.7       37.07     0.469     7.185  ...        38      YES  0.045764     0
3   33.4       32.18     0.458     6.998  ...        45      YES  0.047151     0
4   36.2       32.18     0.458     7.147  ...        55      YES  0.039474     0

[5 rows x 19 columns]

In [ ]:
df.describe()

price  resid_area    air_qual  ...    rainfall       parks        Sold
count  506.000000  506.000000  506.000000  ...  506.000000  506.000000  506.000000
mean    22.528854   41.136779    0.554695  ...   39.181818    0.054454    0.454545
std      9.182176    6.860353    0.115878  ...   12.513697    0.010632    0.498422
min      5.000000   30.460000    0.385000  ...    3.000000    0.033292    0.000000
25%     17.025000   35.190000    0.449000  ...   28.000000    0.046464    0.000000
50%     21.200000   39.690000    0.538000  ...   39.000000    0.053507    0.000000
75%     25.000000   48.100000    0.624000  ...   50.000000    0.061397    1.000000
max     50.000000   57.740000    0.871000  ...   60.000000    0.086711    1.000000

[8 rows x 16 columns]

In [ ]:
uv = np.percentile(df.n_hot_rooms,[99])[0]

df.n_hot_rooms[df.n_hot_rooms>3*uv] = 3*uv

In [ ]:
lv = np.percentile(df.rainfall,[1])[0]
df.rainfall[(df.rainfall < 0.3*lv)] = 0.3*lv

In [ ]:
df.n_hos_beds = df.n_hos_beds.fillna(df.n_hos_beds.mean())

In [ ]:
df['avg_dist'] = (df.dist1+df.dist2+df.dist3+df.dist4)/4

df = df.drop(columns=["dist1", "dist2", "dist3", "dist4"], axis=1)

In [ ]:
del df['bus_ter']

In [ ]:
df = pd.get_dummies(df)

del df['airport_NO']
del df['waterbody_None']


df.head()

price  resid_area  ...  waterbody_Lake and River  waterbody_River
0   24.0       32.31  ...                         0                1
1   21.6       37.07  ...                         0                0
2   34.7       37.07  ...                         0                0
3   33.4       32.18  ...                         0                0
4   36.2       32.18  ...                         0                0

[5 rows x 17 columns]

In [ ]:
df.to_csv('/content/drive/MyDrive/Data Science Notes with Example/Data Files/2. ST Academy - Classification models resource files/House-Price_cleaned.csv', index=False)

# Examples

## Logistic Regression 

**Importing Data**

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Data Science Notes with Example/Data Files/2. ST Academy - Classification models resource files/House-Price_cleaned.csv")
df.head()

price  resid_area  ...  waterbody_Lake and River  waterbody_River
0   24.0       32.31  ...                         0                1
1   21.6       37.07  ...                         0                0
2   34.7       37.07  ...                         0                0
3   33.4       32.18  ...                         0                0
4   36.2       32.18  ...                         0                0

[5 rows x 17 columns]

1. **Prediction Question:**
Will the house pe sold within three months of getting listed?

2. **Inferential Question:**
How accurately can we estimate the effect of each if the predictor variables on the response variable?

**Using one variable for classification**

In [3]:
X = df[["price"]]
y = df["Sold"]

**Using Sklearn library**

In [ ]:
# import Logistic regression model
from sklearn.linear_model import LogisticRegression

In [ ]:
# object of Logistic regression
clf_lrs = LogisticRegression()

# Fitting the model
clf_lrs.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
# printing coefficient and intercept
clf_lrs.coef_, clf_lrs.intercept_

(array([[-0.03571865]]), array([0.61477516]))

**Using Statsmodel**

In [ ]:
# import library
import statsmodels.api as sn
import statsmodels.discrete.discrete_model as sm

In [ ]:
# Adding constant variable on train data
X_cons = sn.add_constant(X)
X_cons.head()

const  price
0    1.0   24.0
1    1.0   21.6
2    1.0   34.7
3    1.0   33.4
4    1.0   36.2

In [ ]:
# fitting 
logit = sm.Logit(y,X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.676690
         Iterations 5


In [ ]:
# summary of logit model
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Tue, 08 Jun 2021   Pseudo R-squ.:                 0.01788
Time:                        09:38:32   Log-Likelihood:                -342.41
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 0.0004142
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6149      0.248      2.484      0.013       0.130       1.100
price         -0.0357      0.010     -3.417      0.001      -0.056      -0.015
==============================================================================
"""

## Prediction and Confusion Matrix

In [ ]:
# predicting on X data and assigning True to probability greater than 0.5 value and storing on y_pred
y_pred = (clf_lrs.predict_proba(X)[:,1]>=0.5)

In [ ]:
# confusion matrix
from sklearn.metrics import confusion_matrix

confusion_matrix(y,y_pred)

array([[208,  68],
       [165,  65]])

In [ ]:
# importing libraries
from sklearn.metrics import precision_score, recall_score, roc_auc_score

In [ ]:
# precission score
precision_score(y,y_pred)

0.48872180451127817

In [ ]:
# recall score
recall_score(y,y_pred)

0.2826086956521739

In [ ]:
# roc auc score
roc_auc_score(y,y_pred)

0.5181159420289855

## Logistic Regression for multiple predictor

In [ ]:
# data
X = df.loc[:,df.columns != "Sold"]
y = df["Sold"]

**Using Sklearn**

In [ ]:
# import Logistic regression model
from sklearn.linear_model import LogisticRegression

In [ ]:
# object of Logistic regression
clf_lr = LogisticRegression()

# Fitting the model
clf_lr.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

**Using statsmodels**

In [ ]:
# importing libraries
import statsmodels.api as sn
import statsmodels.discrete.discrete_model as sm

In [ ]:
# adding constant variable to train data
X_cons = sn.add_constant(X)
y = df["Sold"]
X_cons.head()

const  price  ...  waterbody_Lake and River  waterbody_River
0    1.0   24.0  ...                         0                1
1    1.0   21.6  ...                         0                0
2    1.0   34.7  ...                         0                0
3    1.0   33.4  ...                         0                0
4    1.0   36.2  ...                         0                0

[5 rows x 17 columns]

In [ ]:
# fitting logit model
logit = sm.Logit(y,X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.556433
         Iterations 6


In [ ]:
# summary of logit model
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      489
Method:                           MLE   Df Model:                           16
Date:                Tue, 08 Jun 2021   Pseudo R-squ.:                  0.1924
Time:                        10:14:41   Log-Likelihood:                -281.56
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 9.930e-21
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -2.1383      2.649     -0.807      0.420      -7.331       3.054
price                       -0.2741      0.033     -8.313      0.000      -0.339      -0.209
resid_area                   0.0192      0.027      0.720      0.471      -0.033       0.071
air_qual                    -7.4183      2.691     -2.757      0.006     -12.693      -2.144
room_num                     1.1067      0.277      4.001      0.000       0.565       1.649
age                         -0.0020      0.007     -0.302      0.762      -0.015       0.011
teachers                     0.3150      0.064      4.937      0.000       0.190       0.440
poor_prop                   -0.2077      0.034     -6.149      0.000      -0.274      -0.141
n_hos_beds                   0.1760      0.071      2.467      0.014       0.036       0.316
n_hot_rooms                 -0.0742      0.052     -1.439      0.150      -0.175       0.027
rainfall                    -0.0033      0.008     -0.394      0.693      -0.020       0.013
parks                       29.1089     24.177      1.204      0.229     -18.277      76.495
avg_dist                    -0.4017      0.098     -4.118      0.000      -0.593      -0.211
airport_YES                 -0.1524      0.211     -0.723      0.469      -0.565       0.261
waterbody_Lake              -0.1032      0.304     -0.340      0.734      -0.698       0.492
waterbody_Lake and River    -0.0626      0.328     -0.191      0.849      -0.705       0.580
waterbody_River              0.2394      0.256      0.937      0.349      -0.262       0.740
============================================================================================
"""

## Linear Discriminant Analysis

In [ ]:
# importing LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import train_test_split

In [ ]:
# read csv data
df = pd.read_csv("/content/drive/MyDrive/Data Science Notes with Example/Data Files/2. ST Academy - Classification models resource files/House-Price_cleaned.csv")

# predictor variable
X = df.loc[:,df.columns != "Sold"]

# response variable
y = df["Sold"]

In [ ]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# object of LDA
clf_lda = LinearDiscriminantAnalysis()

# fitting on X and y data
clf_lda.fit(X_train,y_train)

LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
                           solver='svd', store_covariance=False, tol=0.0001)

In [ ]:
# predicting 
y_pred_lda = clf_lda.predict(X_test)

In [ ]:
# importing libraries
from sklearn.metrics import confusion_matrix, roc_auc_score, accuracy_score

confusion_matrix(y_test, y_pred_lda)

array([[41, 19],
       [11, 31]])

In [ ]:
accuracy_score(y_test, y_pred_lda)

0.7058823529411765

In [ ]:
roc_auc_score(y_test, y_pred_lda)

0.7107142857142857

## K-Nearest Neighbors

In [22]:
X = df.loc[:,df.columns != "Sold"]
y = df["Sold"]

from sklearn.model_selection import train_test_split

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
# Scaling the data
from sklearn import preprocessing

# fitting scaler object on X_train
scaler = preprocessing.StandardScaler().fit(X_train)

In [24]:
# transform the X_train and X_test using scaler object
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [40]:
from sklearn.neighbors import KNeighborsClassifier

clf_knn = KNeighborsClassifier(n_neighbors=3)

clf_knn.fit(X_train_scaled,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score

# predict response using X_test_scaled data
y_pred = clf_knn.predict(X_test_scaled)

# confusion matrix
confusion_matrix(y_test,y_pred)

array([[34, 26],
       [14, 28]])

In [42]:
# accuracy score
accuracy_score(y_test,y_pred)

0.6078431372549019

### GridSearchCv finding best n_neighbors

In [43]:
from sklearn.model_selection import GridSearchCV

In [62]:
# dictionary of hyperparameter
params = {"n_neighbors":np.arange(1,100)}

grid_search_cv = GridSearchCV(estimator=KNeighborsClassifier(),param_grid=params,
                              scoring="accuracy",n_jobs=-1,return_train_score=True,verbose=1)

In [63]:
# fitting grid_search_cv on X_train_scaled and y_train
grid_search_cv.fit(X_train_scaled,y_train,)

Fitting 5 folds for each of 99 candidates, totalling 495 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done 164 tasks      | elapsed:    3.0s
[Parallel(n_jobs=-1)]: Done 495 out of 495 | elapsed:    9.8s finished


GridSearchCV(cv=None, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=-1,
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scori

In [64]:
# best params of grid search
grid_search_cv.best_params_

{'n_neighbors': 95}

In [65]:
# getting best classifier from grid search
best_clf_knn = grid_search_cv.best_estimator_

In [66]:
# predict X_test_scaled using best classifier
y_pred = best_clf_knn.predict(X_test_scaled)

In [67]:
# confusion matrix using best classifier
confusion_matrix(y_test,y_pred)

array([[38, 22],
       [16, 26]])

In [68]:
# accuracy score using best classifier
accuracy_score(y_test,y_pred)

0.6274509803921569