In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import math

In [2]:
test = pd.read_csv(r"C:\dataset\test_gradient.csv")
test

x   y
0  92  98
1  56  68
2  88  81
3  70  80
4  80  83
5  49  52
6  65  66
7  35  30
8  66  68
9  67  73

In [3]:
test.shape

(10, 2)

In [4]:
test_x = np.array(test['x'])
test_x

array([92, 56, 88, 70, 80, 49, 65, 35, 66, 67], dtype=int64)

In [5]:
test_y = np.array(test['y'])
test_y

array([98, 68, 81, 80, 83, 52, 66, 30, 68, 73], dtype=int64)

In [6]:
reg = linear_model.LinearRegression()
reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
reg.fit(test[['x']], test['y'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
reg.coef_

array([1.01773624])

In [9]:
reg.intercept_

1.9152193111568891

In [10]:
'''
y = mx + c
mse(cost function) = (1/n)*sum(y-(y predicted('mx+c')))**2
mse = (1/n)*sum(y-(mx+c))**2
partial derevative of mse with m (dm) = -(2/n)*sum(x*(y-(mx+c)))
partial derevative of mse with c (dc) = -(2/n)*sum(y-(mx+c))
'''

def gradientDescent(x, y):
    m_curr = c_curr = 0
    iteration = 1000000
    learning_rate = 0.0002
    n = len(x)
    cost_previous = 0
    
    for i in range(iteration):
        y_predict = m_curr*x + c_curr
        cost = (1/n)*sum([val**2 for val in (y-y_predict)])
        dm = -(2/n)*sum(x*(y-y_predict))
        dc = -(2/n)*sum(y-y_predict)
        m_curr = m_curr - learning_rate*dm
        c_curr = c_curr - learning_rate*dc
        if math.isclose(cost, cost_previous, rel_tol=1e-20):
            break
        cost_previous = cost
    print(f"m {m_curr} c {c_curr} cost {cost} iteration {i}")
    return m_curr, c_curr
        
m, c = gradientDescent(test_x, test_y)

m 1.0177381667350405 c 1.9150826165722297 cost 31.604511334602297 iteration 415533


In [11]:
print(f"Using gradient descent function: Coef = {m} Intercept = {c}")

Using gradient descent function: Coef = 1.0177381667350405 Intercept = 1.9150826165722297


In [12]:
coef = reg.coef_
intercept = reg.intercept_
print(f"Using sklearn: Coef = {coef} Intercept = {intercept}")

Using sklearn: Coef = [1.01773624] Intercept = 1.9152193111568891
